/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author PERSONAL
 */
public class JAltaProveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form JAltaProveedor
     */
    public JAltaProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setTitle("Alta de Proveedor");
        getContentPane().setLayout(null);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(151, 20, 84, 20);

        jLabel13.setText("Nickname:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(71, 20, 49, 14);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(151, 50, 84, 20);

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(71, 50, 41, 14);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(151, 80, 84, 20);

        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(71, 80, 41, 14);

        jLabel4.setText("Email:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(71, 110, 28, 14);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(151, 110, 84, 20);

        jLabel9.setText("AÑO");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(241, 150, 22, 14);

        jLabel8.setText("MES");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(181, 150, 20, 14);

        jLabel7.setText("DIA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 150, 18, 14);

        jLabel5.setText("Fecha de nacimiento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 150, 102, 14);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(139, 258, 114, 20);

        jLabel10.setText("Empresa:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(69, 218, 45, 14);

        jLabel11.setText("Nombre:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(89, 258, 41, 14);

        jLabel12.setText("Link:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(89, 298, 22, 14);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(139, 298, 114, 20);

        jLabel6.setText("Imagen:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(69, 348, 40, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(123, 180, 40, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(181, 180, 40, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(227, 180, 56, 20);

        jButton1.setText("Examinar");
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 380, 80, 23);

        jButton2.setText("ACEPTAR");
        getContentPane().add(jButton2);
        jButton2.setBounds(70, 440, 79, 23);

        jButton3.setText("CANCELAR");
        getContentPane().add(jButton3);
        jButton3.setBounds(160, 440, 85, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 350, 110, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
