/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author PERSONAL
 */
public class JAltaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form JAltaCliente
     */
    public JAltaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();

        setTitle("Alta de Cliente");
        getContentPane().setLayout(null);

        jButton1.setText("Examinar");
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 360, 90, 23);

        jLabel6.setText("Imagen:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 360, 40, 14);

        jButton2.setText("ACEPTAR");
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 270, 79, 23);

        jButton3.setText("CANCELAR");
        getContentPane().add(jButton3);
        jButton3.setBounds(210, 270, 85, 23);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(200, 190, 40, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(150, 190, 40, 20);

        jLabel9.setText("AÑO");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(260, 160, 22, 14);

        jLabel8.setText("MES");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(210, 160, 20, 14);

        jLabel5.setText("Fecha de nacimiento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 160, 102, 14);

        jLabel7.setText("DIA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 160, 18, 14);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(170, 120, 84, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(170, 90, 84, 20);

        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 90, 41, 14);

        jLabel4.setText("Email:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 120, 28, 14);

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 60, 41, 14);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(170, 30, 84, 20);

        jLabel13.setText("Nickname:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(90, 30, 49, 14);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(170, 60, 84, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(250, 190, 56, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
