/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import Logica.Reserva;
import Logica.Sistema;
import java.util.Map;
/**
 *
 * @author PERSONAL
 */
public class JCancelarReserva extends javax.swing.JInternalFrame {

    /**
     * Creates new form JCancelarReserva
     */
    public JCancelarReserva() {
        Sistema sis = new Sistema();
        Map<Integer, Reserva> map = sis.getReservas();
        for (Integer key : map.keySet()) {
            if(map.get(key).getEstado().toString().equals("CANCELADA")) {
                jcbxCodigo.addItem(key.toString());
            }
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbxCodigo = new javax.swing.JComboBox<>();
        jbtnAceptar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        setTitle("Cacelar Reserva");
        getContentPane().setLayout(null);

        jLabel1.setText("Codigo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 30, 33, 14);

        jcbxCodigo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbxCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(jcbxCodigo);
        jcbxCodigo.setBounds(90, 30, 80, 20);

        jbtnAceptar.setText("ACEPTAR");
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAceptar);
        jbtnAceptar.setBounds(30, 80, 79, 23);

        jbtnCancelar.setText("CANCELAR");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCancelar);
        jbtnCancelar.setBounds(120, 80, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbxCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxCodigoActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
        int codigo = (int) jcbxCodigo.getSelectedItem();
        Sistema sist = new Sistema();
        sist.CancelarReserva(codigo);
        Map<Integer, Reserva> map = sist.getReservas();
        for (Integer key : map.keySet()) {
            if(!map.get(key).getEstado().equals("CANCELADA")) {
                jcbxCodigo.addItem(key.toString());
            }
        }
    }//GEN-LAST:event_jbtnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JComboBox<String> jcbxCodigo;
    // End of variables declaration//GEN-END:variables
}
