/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author joaquin
 */
public class JPrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form principal_administrador
     */
    public JPrincipalAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnUsuario = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmnVerInfoProv = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jmnCliente = new javax.swing.JMenu();
        jmnVerInfoCli = new javax.swing.JMenuItem();
        jmnAltaUsu = new javax.swing.JMenu();
        jmnAltaProv = new javax.swing.JMenuItem();
        jmnAltaCli = new javax.swing.JMenuItem();
        jmnCategoria = new javax.swing.JMenu();
        jmnAltaCategoria = new javax.swing.JMenuItem();
        jmnServicio = new javax.swing.JMenu();
        jmnAltaServicio = new javax.swing.JMenuItem();
        jmnActServicio = new javax.swing.JMenuItem();
        jmnVerInfoServicio = new javax.swing.JMenuItem();
        jmnPromocion = new javax.swing.JMenu();
        jmnAltaPromocion = new javax.swing.JMenuItem();
        jmnVerInfoPromo = new javax.swing.JMenuItem();
        jmnReserva = new javax.swing.JMenu();
        jmnRealizarReserva = new javax.swing.JMenuItem();
        jActEstReserva = new javax.swing.JMenuItem();
        jmnCacelarReserva = new javax.swing.JMenuItem();
        jmnVerInfoReserva = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnSalir.setText("salir");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        jmnUsuario.setText("USUARIO");
        jmnUsuario.add(jSeparator1);

        jmnVerInfoProv.setText("Proveedor");

        jMenuItem10.setText("Ver Info Proveedor");
        jmnVerInfoProv.add(jMenuItem10);

        jmnUsuario.add(jmnVerInfoProv);

        jmnCliente.setText("Cliente");

        jmnVerInfoCli.setText("Ver Info Cliente");
        jmnCliente.add(jmnVerInfoCli);

        jmnUsuario.add(jmnCliente);

        jmnAltaUsu.setText("Alta de Usuario");

        jmnAltaProv.setText("Alta de Proveedor");
        jmnAltaProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnAltaProvActionPerformed(evt);
            }
        });
        jmnAltaUsu.add(jmnAltaProv);

        jmnAltaCli.setText("Alta de Cliente");
        jmnAltaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnAltaCliActionPerformed(evt);
            }
        });
        jmnAltaUsu.add(jmnAltaCli);

        jmnUsuario.add(jmnAltaUsu);

        jMenuBar1.add(jmnUsuario);

        jmnCategoria.setText("CATEGORIA");

        jmnAltaCategoria.setText("Alta de Categoria");
        jmnAltaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnAltaCategoriaActionPerformed(evt);
            }
        });
        jmnCategoria.add(jmnAltaCategoria);

        jMenuBar1.add(jmnCategoria);

        jmnServicio.setText("SERVICIO");

        jmnAltaServicio.setText("Alta de Servicio");
        jmnAltaServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnAltaServicioActionPerformed(evt);
            }
        });
        jmnServicio.add(jmnAltaServicio);

        jmnActServicio.setText("Actualizar Servicio");
        jmnActServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnActServicioActionPerformed(evt);
            }
        });
        jmnServicio.add(jmnActServicio);

        jmnVerInfoServicio.setText("Ver Info Servicio");
        jmnServicio.add(jmnVerInfoServicio);

        jMenuBar1.add(jmnServicio);

        jmnPromocion.setText("PROMOCION");

        jmnAltaPromocion.setText("Alta de Promocion");
        jmnAltaPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnAltaPromocionActionPerformed(evt);
            }
        });
        jmnPromocion.add(jmnAltaPromocion);

        jmnVerInfoPromo.setText("Ver Info Promocion");
        jmnPromocion.add(jmnVerInfoPromo);

        jMenuBar1.add(jmnPromocion);

        jmnReserva.setText("RESERVA");

        jmnRealizarReserva.setText("Realizar Reserva");
        jmnReserva.add(jmnRealizarReserva);

        jActEstReserva.setText("Actualizar Estado de Reserva");
        jmnReserva.add(jActEstReserva);

        jmnCacelarReserva.setText("Cancelar Reserva");
        jmnReserva.add(jmnCacelarReserva);

        jmnVerInfoReserva.setText("Ver Info Reserva");
        jmnReserva.add(jmnVerInfoReserva);

        jMenuBar1.add(jmnReserva);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(468, Short.MAX_VALUE)
                .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jmnAltaPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnAltaPromocionActionPerformed
       JAltaPromocion jpromo = new JAltaPromocion();
       jpromo.setVisible(true);
    }//GEN-LAST:event_jmnAltaPromocionActionPerformed

    private void jmnAltaServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnAltaServicioActionPerformed
        JAltaServicio jservicio = new JAltaServicio();
        jservicio.setVisible(true);
    }//GEN-LAST:event_jmnAltaServicioActionPerformed

    private void jmnActServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnActServicioActionPerformed
        JActualizarServicio jactserv = new JActualizarServicio();
        jactserv.setVisible(true);
    }//GEN-LAST:event_jmnActServicioActionPerformed

    private void jmnAltaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnAltaCliActionPerformed
        JAltaCliente jcli = new JAltaCliente();
        jcli.setVisible(true);
    }//GEN-LAST:event_jmnAltaCliActionPerformed

    private void jmnAltaProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnAltaProvActionPerformed
        JAltaProveedor jprov = new JAltaProveedor();
        jprov.setVisible(true);
    }//GEN-LAST:event_jmnAltaProvActionPerformed

    private void jmnAltaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnAltaCategoriaActionPerformed
        JAltaCategoria jcat = new JAltaCategoria();
        jcat.setVisible(true);
    }//GEN-LAST:event_jmnAltaCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jActEstReserva;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JMenuItem jmnActServicio;
    private javax.swing.JMenuItem jmnAltaCategoria;
    private javax.swing.JMenuItem jmnAltaCli;
    private javax.swing.JMenuItem jmnAltaPromocion;
    private javax.swing.JMenuItem jmnAltaProv;
    private javax.swing.JMenuItem jmnAltaServicio;
    private javax.swing.JMenu jmnAltaUsu;
    private javax.swing.JMenuItem jmnCacelarReserva;
    private javax.swing.JMenu jmnCategoria;
    private javax.swing.JMenu jmnCliente;
    private javax.swing.JMenu jmnPromocion;
    private javax.swing.JMenuItem jmnRealizarReserva;
    private javax.swing.JMenu jmnReserva;
    private javax.swing.JMenu jmnServicio;
    private javax.swing.JMenu jmnUsuario;
    private javax.swing.JMenuItem jmnVerInfoCli;
    private javax.swing.JMenuItem jmnVerInfoPromo;
    private javax.swing.JMenu jmnVerInfoProv;
    private javax.swing.JMenuItem jmnVerInfoReserva;
    private javax.swing.JMenuItem jmnVerInfoServicio;
    // End of variables declaration//GEN-END:variables
}
