/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.Cliente;
import Logica.Promocion;
import Logica.Reserva;
import Logica.Servicio;
import Logica.Sistema;
import static java.lang.Integer.parseInt;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author PERSONAL
 */
public class JRealizarReserva extends javax.swing.JInternalFrame {
    HashMap <Integer, Dt_Serv> dt_servicios;
    HashMap <String, Dt_Promo> dt_promociones;
    /**
     * Creates new form JRealizarReserva
     */
    public JRealizarReserva() {
        Sistema sis = new Sistema();
        Map<String, Cliente> cli = sis.getClientes();
        for (String key : cli.keySet()) {
            jcbxClientes.addItem(key);
        }
        Map<Integer, Servicio> serv = sis.getServicios();
        for (Integer key : serv.keySet()) {
            jcbxServicios.addItem(key.toString());
        }
        Map<String, Promocion> promo = sis.getPromociones();
        for (String key : promo.keySet()) {
            jcbxPromociones.addItem(key);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbxServicios = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFechaIniServ = new com.toedter.calendar.JDateChooser();
        jFechaFinServ = new com.toedter.calendar.JDateChooser();
        jtxtPrecio = new javax.swing.JTextField();
        jcbxClientes = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jcbxPromociones = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFechaIniPromo = new com.toedter.calendar.JDateChooser();
        jFechaFinPromo = new com.toedter.calendar.JDateChooser();
        jbtnIngresarServ = new javax.swing.JButton();
        jbtnIngresarPromo = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jtxtCantidadServ = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtCantidadPromo = new javax.swing.JTextField();
        jbtnAceptar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        setTitle("Realizar Reserva");
        getContentPane().setLayout(null);

        jLabel1.setText("Precio Total:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 60, 14);

        jLabel2.setText("Cliente:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 50, 14);

        jLabel3.setText("SERVICIO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 120, 60, 14);

        jcbxServicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbxServicios);
        jcbxServicios.setBounds(90, 150, 56, 20);

        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 41, 14);

        jLabel5.setText("Fecha Inicio:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 180, 70, 14);

        jLabel6.setText("Fecha Fin:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 210, 50, 14);
        getContentPane().add(jFechaIniServ);
        jFechaIniServ.setBounds(90, 180, 110, 20);
        getContentPane().add(jFechaFinServ);
        jFechaFinServ.setBounds(90, 210, 110, 20);
        getContentPane().add(jtxtPrecio);
        jtxtPrecio.setBounds(90, 30, 70, 20);

        jcbxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbxClientes);
        jcbxClientes.setBounds(90, 60, 90, 20);

        jLabel7.setText("PROMOCION:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 120, 70, 14);

        jcbxPromociones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbxPromociones);
        jcbxPromociones.setBounds(310, 150, 56, 20);

        jLabel8.setText("Nombre:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 150, 41, 14);

        jLabel9.setText("Fecha Inicio:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(240, 180, 70, 14);

        jLabel10.setText("Fecha Fin:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(240, 210, 50, 14);
        getContentPane().add(jFechaIniPromo);
        jFechaIniPromo.setBounds(310, 180, 110, 20);
        getContentPane().add(jFechaFinPromo);
        jFechaFinPromo.setBounds(310, 210, 110, 20);

        jbtnIngresarServ.setText("Ingresar");
        jbtnIngresarServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresarServActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnIngresarServ);
        jbtnIngresarServ.setBounds(100, 270, 73, 23);

        jbtnIngresarPromo.setText("Ingresar");
        jbtnIngresarPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresarPromoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnIngresarPromo);
        jbtnIngresarPromo.setBounds(340, 270, 73, 23);

        jLabel11.setText("Cantidad:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 240, 50, 14);
        getContentPane().add(jtxtCantidadServ);
        jtxtCantidadServ.setBounds(90, 240, 30, 20);

        jLabel12.setText("Cantidad:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(240, 240, 50, 14);
        getContentPane().add(jtxtCantidadPromo);
        jtxtCantidadPromo.setBounds(310, 240, 30, 20);

        jbtnAceptar.setText("ACEPTAR");
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAceptar);
        jbtnAceptar.setBounds(150, 320, 90, 23);

        jbtnCancelar.setText("CANCELAR");
        getContentPane().add(jbtnCancelar);
        jbtnCancelar.setBounds(250, 320, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
        Sistema sist = new Sistema();
        Reserva res = new Reserva();
        int cod = res.getCod();
        //Map<Integer, Reserva> map = sist.getReservas();
        HashMap <Integer,Reserva> reservas;
        
    }//GEN-LAST:event_jbtnAceptarActionPerformed

    private void jbtnIngresarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresarServActionPerformed
        Integer nombre = (Integer) jcbxServicios.getSelectedItem();
        Date fecha_ini = jFechaIniServ.getDate();
        Date fecha_fin = jFechaFinServ.getDate();
        int cantidad = parseInt(jtxtCantidadServ.getText());
        Dt_Serv serv = new Dt_Serv(nombre,fecha_ini,fecha_fin, cantidad);
        dt_servicios.put(nombre, serv);
    }//GEN-LAST:event_jbtnIngresarServActionPerformed

    private void jbtnIngresarPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresarPromoActionPerformed
       String nombre = (String) jcbxPromociones.getSelectedItem();
       Date fecha_ini = jFechaIniPromo.getDate();
       Date fecha_fin = jFechaFinPromo.getDate();
       int cantidad = parseInt(jtxtCantidadPromo.getText());
       Dt_Promo promo = new Dt_Promo(nombre,fecha_ini,fecha_fin, cantidad);
       dt_promociones.put(nombre, promo);
    }//GEN-LAST:event_jbtnIngresarPromoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jFechaFinPromo;
    private com.toedter.calendar.JDateChooser jFechaFinServ;
    private com.toedter.calendar.JDateChooser jFechaIniPromo;
    private com.toedter.calendar.JDateChooser jFechaIniServ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnIngresarPromo;
    private javax.swing.JButton jbtnIngresarServ;
    private javax.swing.JComboBox<String> jcbxClientes;
    private javax.swing.JComboBox<String> jcbxPromociones;
    private javax.swing.JComboBox<String> jcbxServicios;
    private javax.swing.JTextField jtxtCantidadPromo;
    private javax.swing.JTextField jtxtCantidadServ;
    private javax.swing.JTextField jtxtPrecio;
    // End of variables declaration//GEN-END:variables
}
