/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.Cliente;
import Logica.Dt_promo;
import Logica.Estado;
import static Logica.Estado.REGISTRADA;
import Logica.Fecha;
import Logica.Promocion;
import Logica.Reserva;
import Logica.Servicio;
import Logica.Sistema;
import static java.lang.Integer.parseInt;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author PERSONAL
 */
public class JRealizarReserva extends javax.swing.JInternalFrame {
    //HashMap <Integer, Dt_Serv> dt_servicios;
    HashMap <String, Dt_promo> dt_promociones;
    Dt_promo promo;
    /**
     * Creates new form JRealizarReserva
     */
    public JRealizarReserva() {
        Sistema sis = Sistema.getInstance();
        Map<String, Cliente> cli = sis.getClientes();
        for (String key : cli.keySet()) {
            jcbxClientes.addItem(key);
        }
        Map<Integer, Servicio> serv = sis.getServicios();
        for (Integer key : serv.keySet()) {
            jcbxServicios.addItem(key.toString());
        }
        Map<String, Promocion> promo = sis.getPromociones();
        for (String key : promo.keySet()) {
            jcbxPromociones.addItem(key);
        }
        
        initComponents();
    }
        String nombre_serv_promo;
        Fecha fecha_ini, fecha_fin;
        int cantidad;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbxServicios = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtxtPrecio = new javax.swing.JTextField();
        jcbxClientes = new javax.swing.JComboBox<>();
        jcbxPromociones = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFechaIniPromo = new com.toedter.calendar.JDateChooser();
        jFechaFinPromo = new com.toedter.calendar.JDateChooser();
        jbtnIngresarServ = new javax.swing.JButton();
        jbtnIngresarPromo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jtxtCantidadPromo = new javax.swing.JTextField();
        jbtnAceptar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        setTitle("Realizar Reserva");
        getContentPane().setLayout(null);

        jLabel1.setText("Precio Total:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 60, 14);

        jLabel2.setText("Cliente:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 50, 14);

        jLabel3.setText("Seleccione el Servicio o Promoción");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 120, 170, 14);

        jcbxServicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbxServicios);
        jcbxServicios.setBounds(110, 150, 56, 20);

        jLabel4.setText("Servicios:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 46, 14);
        getContentPane().add(jtxtPrecio);
        jtxtPrecio.setBounds(90, 30, 70, 20);

        jcbxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbxClientes);
        jcbxClientes.setBounds(90, 60, 90, 20);

        jcbxPromociones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbxPromociones);
        jcbxPromociones.setBounds(110, 180, 56, 20);

        jLabel8.setText("Promociones:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 180, 70, 14);

        jLabel9.setText("Fecha Inicio:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 210, 70, 14);

        jLabel10.setText("Fecha Fin:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 240, 50, 14);
        getContentPane().add(jFechaIniPromo);
        jFechaIniPromo.setBounds(110, 210, 110, 20);
        getContentPane().add(jFechaFinPromo);
        jFechaFinPromo.setBounds(110, 240, 110, 20);

        jbtnIngresarServ.setText("Ingresar Servicio");
        jbtnIngresarServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresarServActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnIngresarServ);
        jbtnIngresarServ.setBounds(3, 310, 113, 30);

        jbtnIngresarPromo.setText("Ingresar Promo");
        jbtnIngresarPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresarPromoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnIngresarPromo);
        jbtnIngresarPromo.setBounds(133, 310, 110, 30);

        jLabel12.setText("Cantidad:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 270, 50, 14);
        getContentPane().add(jtxtCantidadPromo);
        jtxtCantidadPromo.setBounds(110, 270, 30, 20);

        jbtnAceptar.setText("ACEPTAR");
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAceptar);
        jbtnAceptar.setBounds(50, 370, 90, 20);

        jbtnCancelar.setText("CANCELAR");
        getContentPane().add(jbtnCancelar);
        jbtnCancelar.setBounds(150, 370, 90, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
        Sistema sist = new Sistema();
        Reserva res = new Reserva();
        int cod = res.getCod();
        int preciototal = parseInt(jtxtPrecio.getText());
        String cliente = (String) jcbxClientes.getSelectedItem();
        Calendar c1 = Calendar.getInstance();
        //Calendar c2 = new GregorianCalendar();
        int dia = c1.get(Calendar.DATE);
        int mes = c1.get(Calendar.MONTH)+1;
        int anio = c1.get(Calendar.YEAR);
        Fecha fecha_creado = new Fecha(dia,mes,anio);
        HashMap <Integer,Reserva> reservas;
        sist.RealizarReserva(cod,fecha_creado, preciototal,cliente, dt_servicios, dt_promociones);
        
    }//GEN-LAST:event_jbtnAceptarActionPerformed

    private void jbtnIngresarPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresarPromoActionPerformed
       nombre_serv_promo = (String) jcbxPromociones.getSelectedItem();
       fecha_ini = new Fecha(jFechaIniPromo.getDate().getDay(),jFechaIniPromo.getDate().getMonth(), jFechaIniPromo.getDate().getYear());
       fecha_fin = new Fecha(jFechaFinPromo.getDate().getDay(),jFechaFinPromo.getDate().getMonth(), jFechaFinPromo.getDate().getYear());
       cantidad = parseInt(jtxtCantidadPromo.getText());
       promo = new Dt_promo(nombre_serv_promo,fecha_ini,fecha_fin, cantidad);
       dt_promociones.put(nombre_serv_promo, promo);
    }//GEN-LAST:event_jbtnIngresarPromoActionPerformed

    private void jbtnIngresarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresarServActionPerformed
        nombre_serv_promo = (String) jcbxServicios.getSelectedItem();
       fecha_ini = new Fecha(jFechaIniPromo.getDate().getDay(),jFechaIniPromo.getDate().getMonth(), jFechaIniPromo.getDate().getYear());
       fecha_fin = new Fecha(jFechaFinPromo.getDate().getDay(),jFechaFinPromo.getDate().getMonth(), jFechaFinPromo.getDate().getYear());
       cantidad = parseInt(jtxtCantidadPromo.getText());
       promo = new Dt_Promo(nombre_serv_promo,fecha_ini,fecha_fin, cantidad);
       dt_promociones.put(nombre_serv_promo, promo);
    }//GEN-LAST:event_jbtnIngresarServActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jFechaFinPromo;
    private com.toedter.calendar.JDateChooser jFechaIniPromo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnIngresarPromo;
    private javax.swing.JButton jbtnIngresarServ;
    private javax.swing.JComboBox<String> jcbxClientes;
    private javax.swing.JComboBox<String> jcbxPromociones;
    private javax.swing.JComboBox<String> jcbxServicios;
    private javax.swing.JTextField jtxtCantidadPromo;
    private javax.swing.JTextField jtxtPrecio;
    // End of variables declaration//GEN-END:variables
}
